development:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole
  pool: 1000
  username: postgres
  password: yuanjing

test: &test
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole_test
  pool: 1000
  username: postgres
  password: yuanjing

cucumber:
  <<: *test