development:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole
  pool: 5
  username: postgres
  password: yuanjing

test:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole
  pool: 5
  username: postgres
  password: yuanjing

development:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole
  pool: 5
  username: postgres
  password: yuanjing