development:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole
  pool: 5
  username: postgres
  password: yuanjing

test:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole_test
  pool: 5
  username: postgres
  password: yuanjing

production:
  adapter: postgresql
  encoding: unicode
  database: COMM013_Mole_Production
  pool: 5
  username: postgres
  password: yuanjing